# -*- coding: utf-8 -*-
"""2_CVI_Python_Plotting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w6WHRzaCqNJe1d-Z998TDgwx3aqgWyvX

# Análise e Visualização de Dados com Python 🐍


---

**Objetivos:**
* Conhecer o método plot() da biblioteca Pandas para gerar gráficos.
* Implementar em código Python a geração de gráficos através de DataFrames.
* Personalizar os gráficos através de opções de configuração disponíveis.
* Exportar gráficos usando o módulo Pyplot.

Ao longo deste *notebook*, deve preencher o código quando indicado com a seguinte marcação:
```python
### INSERIR CÓDIGO AQUI ###
```

Bom trabalho!

## 1. Exemplo Prático - Titanic

Nesta secção, iremos analisar o conjunto de dados do Titanic, carregado num DataFrame. De seguida, pretendemos gerar algumas representações dos dados, nomeadamente:

1. A distribuição por sexo;
2. A distribuição por classe;
3. A distribuição por porto de embarque (gráfico horizontal);
4. Histograma das idades.
"""

# Importar o módulo Pandas
import pandas as pd

# Importar o módulo matplotlib
import matplotlib.pyplot as plt

dados = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

# Imprimir as primeiras 5 linhas dos dados
dados.head()

# Inspecionar os nomes das colunas
dados.columns

# Obter informação global do conjunto de dados
dados.info()

"""## 1.1 Plotting com Pandas

O Pandas usa o método `plot()` para criar diagramas a partir de um DataFrame.

O submódulo Pyplot, da biblioteca Matplotlib, permite visualizar o diagrama no ecrã, bem como personalizar alguns parâmetros (título, nomes dos eixos, cores, etc.) e exportar os

Para import o submódulo Pyplot do Matplotlib, devemos indicar a seguinte linha no cabeçalho do nosso código:

```python
import matplotlib.pyplot as plt
```

## 1.2 Gráfico de barras

Para gerar um visualização que permita mostrar a distribuição por sexo, recorremos a um gráfico de barras. No entanto, primeiro necessitamos de saber quais os valores para cada classe (sexo), para posteriormente gerar o gráfico.

No método `plot()` existe um argumento (`kind`) que permite especificar o tipo de gráfico que pretendemos constuir. Algumas das opções disponíveis estão listadas a seguir:

* 'line' : line plot (default)
* 'bar' : vertical bar plot
* 'barh' : horizontal bar plot
* 'hist' : histogram
* 'box' : boxplot
* 'kde' : Kernel Density Estimation plot
* 'density' : same as 'kde'
* 'area' : area plot
* 'pie' : pie plot
* 'scatter' : scatter plot (DataFrame only)
* 'hexbin' : hexbin plot (DataFrame only)
"""

# Obter a contagem por classe
sex_counts = dados["Sex"].value_counts()
print(sex_counts)

# Criar o gráfico de barras
"""
Vamos usar o método plot() associada à variável 'sex_counts',
uma vez que esta contem os valores (contagem) para cada classe
"""
sex_counts.plot(kind='bar')

# Adicionar título geral (title) e nomes dos eixos (xlabel e ylabel)
sex_counts.plot(kind='bar',
                title='Número de passageiros por género',
                xlabel='Género',
                ylabel='Número')

"""## 1.3 Gráfico circular

Para gerar um visualização que permita mostrar a distribuição por classe, podemos explorar o uso de um gráfico circular. No entanto, primeiro necessitamos de saber quais os valores para cada classe (1ª, 2ª, 3ª), através do método `value_counts()` associado à coluna `dados['PClass']`, para posteriormente gerar o gráfico do tipo `kind='pie'`.
"""

# Obter a contagem por classe de passageiro
pclass_counts = dados["Pclass"].value_counts()
print(pclass_counts)

# Criar o gráfico circular
pclass_counts.plot(kind='pie',
                title='classe de passageiros',
                xlabel='classe',
                ylabel='Número')

# 1. Adicione o título "Distribuição dos passageiros por classe"
# 2. Adicione a legenda para o eixo dos yy "Classe do Passageiro"
pclass_counts.plot(kind='pie',
                   title="Distribuição dos passageiros por classe",
                   ylabel="Classe do Passageiro")

"""## 1.4 Gráfico de barras horizontal

Para gerar um visualização que permita mostrar a distribuição por porto de embarque, podemos explorar o uso de um gráfico de barras horizontal. No entanto, primeiro necessitamos de saber quais os valores para cada classe (porto de embarque), através do método `value_counts()` associado à coluna `dados['Embarked']`, para posteriormente gerar o gráfico do tipo `kind='barh'`.
"""

# Obter a contagem por classe
embarked_counts = dados["Embarked"].value_counts()
print(embarked_counts)

# Criar o gráfico de barras horizontal
"""
O tipo de plot deve ser kind='barh'
"""
embarked_counts.plot(kind= 'barh')

# 1. Adicione o título "Distribuição dos passageiros por porto de embarque"
# 2. Adicione a legenda para o eixo dos xx "Porto de Embarque"
# 3. Adicione a legenda para o eixo dos yy "Número de passageiros"
pclass_counts.plot(kind='barh',
                   title="Distribuição dos passageiros por porto de embarque",
                   xlabel="Porto de Embarque",
                   ylabel="Número de passageiros")

"""## 1.5 Histograma

Para gerar um visualização que permita mostrar a distribuição das idades, podemos explorar o uso de um histograma. Para tal basta aplicar o método `plot()` à Série `dados['Age']`, especificando o tipo de gráfico como `kind='hist'`. Podemos ainda especificar o número de bins, que permite obter mais ou menos detalhe, consoante o valor. Um valor maior permite obter mais detalhe.
"""

dados['Age'].plot(kind='hist')

# Alterar o número de bins no histograma
dados['Age'].plot(kind='hist', bins=5)

# 1. Alterar o número de bins no histograma para bins=20
dados['Age'].plot(kind='hist', bins=20)

# 1. Adicionar o título para "Distribuição das Idades"
# 2. Adicionar o nome do eixo dos xx como "Idade"
# 3. Adicionar o nome do eixo dos yy como "Frequência"
dados['Age'].plot(kind='hist',
                  bins=10,
                  title="Distribuição das Idades",
                  xlabel="Idade",
                  ylabel="Frequência")

# Podemos ainda alterar a cor das barras através do argumento color
# e a cor do limite através do argumento edgecolor
dados['Age'].plot(kind='hist',
                  bins=10,
                  color='green',
                  edgecolor='black')

"""## 1.5 Exportar o gráfico

Para exportar o gráfico criado com o Pandas, basta usar o método `savefig()` associado ao módulo Pyplot, onde o primeiro argumento é o nome do ficheiro pretendido (`fname`). Existem ainda outros parâmetros úteis, como:

* `dpi`: resolução da imagem (ex: 300 para impressões)
* `box_inches='tight'`: remove espaços desnecessários
* `transparent=True`: fundo transparente
"""

# Criar o gráfico
dados['Age'].plot(kind='hist',
                  bins=10,
                  color='green',
                  edgecolor='black')

# Exportar o gráfico
plt.savefig(fname='histograma_idades.png',
            dpi=300,
            bbox_inches='tight',
            transparent=True)